const GENERIC = [
  /^inspect the component\.?$/i,
  /^fix if necessary\.?$/i,
  /^check the area\.?$/i,
  /^check the faucet\.?$/i,
  /^tighten the connection\.?$/i,
  /^test it\.?$/i,
];

function stepText(step) {
  return String(step?.instruction || step?.instructions || '').trim();
}

// export function evaluateRepairAssessment(assessment) {
//   const issues = [];
//   if (!assessment || typeof assessment !== 'object') {
//     return { ok: false, schemaValid: false, issues: ['missing_assessment'], retryable: false };
//   }
//   const steps = Array.isArray(assessment.diy_guide_steps) ? assessment.diy_guide_steps : [];
//   const diyEligible = assessment.safe_diy_allowed === true && assessment.professional_required !== true;
//   if (diyEligible && steps.length === 0 && !(assessment.diy_steps || []).length) {
//     issues.push('diy_eligible_without_steps');
//   }
//   steps.forEach((step, index) => {
//     const instruction = stepText(step);
//     if (!step?.title) issues.push(`step_${index + 1}_missing_title`);
//     if (instruction.length < 24) issues.push(`step_${index + 1}_instruction_too_short`);
//     if (!step?.expected_result) issues.push(`step_${index + 1}_missing_expected_result`);
//     if (!step?.if_not && !step?.failure_signs) issues.push(`step_${index + 1}_missing_failure_guidance`);
//     if (GENERIC.some((pattern) => pattern.test(instruction))) issues.push(`step_${index + 1}_generic`);
//   });
//   const schemaValid = issues.length === 0;
//   return {
//     ok: schemaValid,
//     schemaValid,
//     issues,
//     retryable: issues.some((issue) => issue.includes('generic') || issue.includes('too_short') || issue.includes('missing')),
//     stepCount: steps.length,
//   };
// }

export function evaluateRepairAssessment(assessment) {
  const issues = [];
  if (!assessment || typeof assessment !== 'object') {
    return { ok: false, schemaValid: false, issues: ['missing_assessment'], retryable: false };
  }

  // Handle case where assessment might arrive as a JSON string inside an object
  let parsedAssessment = assessment;
  if (typeof assessment.ai_assessment === 'string') {
    try {
      parsedAssessment = JSON.parse(assessment.ai_assessment);
    } catch (e) {
      console.error('[assessment] failed to parse nested ai_assessment string', e);
    }
  }

  // Support alternative layout naming constraints generated by the AI
  const steps = Array.isArray(parsedAssessment.diy_guide_steps) 
    ? parsedAssessment.diy_guide_steps 
    : (Array.isArray(parsedAssessment.diy_steps) ? parsedAssessment.diy_steps : []);

  const diyEligible = parsedAssessment.safe_diy_allowed === true && parsedAssessment.professional_required !== true;
  
  if (diyEligible && steps.length === 0) {
    issues.push('diy_eligible_without_steps');
  }

  steps.forEach((step, index) => {
    const instruction = stepText(step);
    
    if (!step?.title) {
      issues.push(`step_${index + 1}_missing_title`);
    }
    if (instruction.length < 10) { // Relaxed constraint from 24 characters to prevent false negatives
      issues.push(`step_${index + 1}_instruction_too_short`);
    }
    if (!step?.expected_result && !step?.expectedResult) {
      issues.push(`step_${index + 1}_missing_expected_result`);
    }
    // Safe loose check for failure guidance naming variations
    if (!step?.if_not && !step?.failure_signs && !step?.ifNot && !step?.failureSigns) {
      issues.push(`step_${index + 1}_missing_failure_guidance`);
    }
    if (GENERIC.some((pattern) => pattern.test(instruction))) {
      issues.push(`step_${index + 1}_generic`);
    }
  });

  // Filter out non-breaking issues so strict validation warnings do not crash the app experience
  const criticalIssues = issues.filter(issue => !issue.includes('too_short') && !issue.includes('generic'));
  const schemaValid = criticalIssues.length === 0;

  return {
    ok: schemaValid,
    schemaValid,
    issues,
    retryable: issues.some((issue) => issue.includes('generic') || issue.includes('too_short') || issue.includes('missing')),
    stepCount: steps.length,
  };
}

