const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{transformSync}=require('esbuild');
const source=transformSync(fs.readFileSync(__dirname+'/auth.ts','utf8'),{loader:'ts',format:'cjs',target:'es2022'}).code;
function harness(store=new Map(),fetchImpl=async()=>{throw Error('offline')}){const exports={},context={exports,module:{exports},window:{localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)},setTimeout,clearTimeout},fetch:fetchImpl,AbortController,console};vm.runInNewContext(source,context);return context.module.exports;}
const user={id:7,role:'homeowner',name:'Returning Homeowner',email:'fixture@example.test',phone:'5550100',address:'123 Fixture St'};
const ok=(data,status=200)=>({ok:status<400,status,json:async()=>data});
test('signup logout signin refresh and fresh-tab module retain authoritative profile',async()=>{const store=new Map(),calls=[];let auth=harness(store,async(url,init)=>{calls.push(url);return ok({ok:true,token:'fixture-token',user});});assert.equal((await auth.signUpUser({...user,password:'fixture-password'})).ok,true);auth.clearSession();assert.equal(auth.getStoredUser(),null);assert.equal((await auth.signInUser('homeowner',user.email,'fixture-password')).ok,true);auth=harness(store,async()=>ok({ok:true,user}));assert.equal((await auth.validateToken()).source,'server');assert.equal(auth.getStoredUser().address,user.address);assert.equal(harness(store).getStoredUser().phone,user.phone);assert.deepEqual(calls,['/api/auth/signup','/api/auth/signin']);});
test('503/429/nonJSON preserve existing account; missing cache returns network not no-account',async()=>{for(const status of [503,429]){const store=new Map(),auth=harness(store,async()=>ok({ok:false},status));auth.saveSession('fixture-token',user);assert.equal((await auth.validateToken()).source,'cached');assert.equal(auth.getStoredToken(),'fixture-token');store.delete('fixbridge-user-cache');assert.equal((await auth.validateToken()).reason,'network');assert.equal(auth.getStoredToken(),'fixture-token');}});
test('explicit 401 with malformed body expires only the current token',async()=>{const auth=harness(new Map(),async()=>({ok:false,status:401,json:async()=>{throw Error('HTML')}}));auth.saveSession('fixture-token',user);assert.equal((await auth.validateToken()).reason,'invalid');assert.equal(auth.getStoredToken(),null);});
test('pending validation cannot resurrect logout or clear a newer login',async()=>{for(const status of [200,401]){let resolve;const auth=harness(new Map(),()=>new Promise(r=>resolve=r));auth.saveSession('old-token',user);const pending=auth.validateToken();auth.clearSession();if(status===401)auth.saveSession('new-token',{...user,id:8,email:'new@example.test'});resolve(ok({ok:true,user},status));assert.equal((await pending).reason,'superseded');assert.equal(auth.getStoredToken(),status===401?'new-token':null);}});
test('old server profile cannot replace a newer same-token saved profile',async()=>{let resolve;const auth=harness(new Map(),()=>new Promise(r=>resolve=r));auth.saveSession('fixture-token',user);const pending=auth.validateToken();auth.saveSession('fixture-token',{...user,address:'456 Saved St'});resolve(ok({ok:true,user}));assert.equal((await pending).reason,'superseded');assert.equal(auth.getStoredUser().address,'456 Saved St');});
test('orphaned malformed caches and invalid auth successes do not create signed-in state',async()=>{const store=new Map([['fixbridge-user-cache',JSON.stringify(user)]]),auth=harness(store,async()=>ok({ok:true}));assert.equal(auth.getStoredUser(),null);assert.equal((await auth.signInUser('homeowner',user.email,'fixture-password')).ok,false);assert.equal(auth.getStoredToken(),null);auth.saveSession('token',{});assert.equal(auth.getStoredToken(),null);});
