import { useEffect, useRef, useState } from "react";
import { Check, Home, Loader2, Pencil, RotateCcw, Upload, X } from "lucide-react";
import { getPropertyCover, getPropertyCoverOptions, preparePropertyCover, savePropertyCover, type PropertyCover, type PropertyCoverStock } from "./propertyCoverApi";

export default function PropertyCoverPicker({propertyId,label,address,onOpenProperty}:{propertyId?:number;label:string;address:string;onOpenProperty:()=>void}){
  const [loaded,setLoaded]=useState<{propertyId:number;cover:PropertyCover}|null>(null),[stock,setStock]=useState<PropertyCoverStock[]>([]),[loading,setLoading]=useState(false),[optionsLoading,setOptionsLoading]=useState(false),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[error,setError]=useState(""),[draft,setDraft]=useState<string|null>(null),[broken,setBroken]=useState<string|null>(null),[retry,setRetry]=useState(0);
  const generation=useRef(0),lock=useRef(false),fileInput=useRef<HTMLInputElement>(null);
  const cover=loaded&&loaded.propertyId===propertyId?loaded.cover:null;
  const source=cover?.kind==="upload"?cover.imageDataUrl:cover?.kind==="stock"?stock.find(item=>item.key===cover.stockKey)?.url||cover.url:"/home-sample-brick.jpg";
  const isSample=cover?.kind!=="upload";
  useEffect(()=>{const current=++generation.current;setLoaded(null);setDraft(null);setEditing(false);setOptionsLoading(false);setError("");setBroken(null);setBusy(false);lock.current=false;if(!propertyId){setLoading(false);return;}setLoading(true);
    void getPropertyCover(propertyId).then(r=>{if(current!==generation.current)return;if(r.ok&&r.cover)setLoaded({propertyId,cover:r.cover});else setError(r.message||"Your saved cover could not be loaded.");setLoading(false);});return()=>{generation.current++;};
  },[propertyId,retry]);
  useEffect(()=>{
    if(!editing||!propertyId||stock.length)return;
    const current=generation.current;let canceled=false;setOptionsLoading(true);
    void getPropertyCoverOptions().then(options=>{if(canceled||current!==generation.current)return;if(options.ok)setStock(Array.isArray(options.stock)?options.stock:[]);else setError(options.message||"Sample cover choices are unavailable. You can still upload your own photo.");setOptionsLoading(false);});
    return()=>{canceled=true;};
  },[editing,propertyId,stock.length]);
  async function save(value:Parameters<typeof savePropertyCover>[1]){if(!propertyId||lock.current)return;lock.current=true;setBusy(true);setError("");const current=generation.current;try{const r=await savePropertyCover(propertyId,value);if(current!==generation.current)return;if(!r.ok||!r.cover){setError(r.message||"Could not save your cover. Please retry.");return;}setLoaded({propertyId,cover:r.cover});setDraft(null);setEditing(false);setBroken(null);}finally{if(current===generation.current){lock.current=false;setBusy(false);}}}
  async function upload(file:File|null){if(!file||busy)return;setBusy(true);setError("");const current=generation.current;try{const data=await preparePropertyCover(file);if(current===generation.current){setDraft(data);setEditing(true);}}catch(e){if(current===generation.current)setError(e instanceof Error?e.message:"Could not prepare this photo.");}finally{if(current===generation.current)setBusy(false);}}
  return <section aria-label="Property cover" className="property-concept-cover overflow-hidden border border-border bg-card">
    <div className="property-concept-photo relative">
      {source&&broken!==source&&!loading?<img key={`${propertyId}-${cover?.version||"sample"}`} src={source} alt={isSample?"Sample cover image chosen for your workspace":`${label} - your uploaded property photo`} className="absolute inset-0 h-full w-full object-cover" onError={()=>{setBroken(source);setError("The saved cover image could not be displayed. Retry or edit the cover.");}}/>:<div className="absolute inset-0 flex items-center justify-center bg-[#ede8df] dark:bg-[#26231d]"><Home className="h-16 w-16 text-[#755a36] dark:text-[#c8a66a]" strokeWidth={1}/></div>}

      <div className="property-concept-tools">{isSample&&!loading&&<span className="property-concept-sample">Sample photo</span>}{propertyId&&<button type="button" aria-expanded={editing} onClick={()=>setEditing(e=>!e)} disabled={busy||loading||!cover} className="property-concept-edit"><Pencil size={13}/>Change photo / style</button>}</div>
    </div>
    <div className="property-concept-address"><div><h2 className="property-concept-label">{label}</h2><p className="property-concept-location">{address}</p></div><button type="button" onClick={onOpenProperty} className="property-concept-view">View property</button></div>
    {error&&<div role="alert" className="flex flex-wrap items-center justify-between gap-3 border-t border-border p-4 text-sm"><p>{error}</p>{!busy&&<button type="button" onClick={()=>setRetry(n=>n+1)} className="font-semibold underline">Retry cover load</button>}</div>}
    {editing&&propertyId&&<div className="space-y-4 border-t border-border p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold">Make this space your own</h3><p className="mt-1 text-xs text-muted-foreground">Add a home photo or choose a sample. This cover is saved only to this property and is separate from repair photos.</p></div><button type="button" aria-label="Close cover editor" disabled={busy} onClick={()=>{setEditing(false);setDraft(null);}} className="rounded-lg p-1.5"><X size={18}/></button></div>
      <input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" aria-label="Upload property cover photo" onChange={e=>{const file=e.target.files?.[0]||null;e.target.value="";void upload(file);}} disabled={busy}/>
      {draft?<div className="space-y-3"><img src={draft} alt="Your new property cover preview" className="max-h-64 w-full rounded-xl object-cover"/><p className="text-xs text-muted-foreground">Preview only — not saved yet.</p><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>void save({kind:"upload",dataUrl:draft})} className="inline-flex items-center gap-2 rounded-full bg-[#dc6b20] px-4 py-2 text-sm font-semibold text-white"><Check size={15}/>Save photo</button><button type="button" disabled={busy} onClick={()=>setDraft(null)} className="rounded-full border border-border px-4 py-2 text-sm">Choose another</button></div></div>:<div className="space-y-4"><button type="button" disabled={busy} onClick={()=>fileInput.current?.click()} className="inline-flex items-center gap-2 rounded-full bg-[#dc6b20] px-4 py-2.5 text-sm font-semibold text-white"><Upload size={15}/>Upload your home photo</button><p className="text-[11px] text-muted-foreground">JPG, PNG, or WebP · up to 12 MB and 16 megapixels. Location metadata is removed from the saved cover.</p>{optionsLoading&&<p role="status" className="text-xs text-muted-foreground">Loading sample cover choices…</p>}<div className="grid gap-3 sm:grid-cols-2">{stock.map(item=><button type="button" key={item.key} disabled={busy} onClick={()=>void save({kind:"stock",stockKey:item.key})} className="overflow-hidden rounded-xl border border-border text-left disabled:opacity-50"><img src={item.url} alt="" className="h-32 w-full object-cover"/><span className="block p-3 text-xs font-medium">{item.label}</span></button>)}</div></div>}
      <div className="flex flex-wrap items-center gap-4"><button type="button" disabled={busy} onClick={()=>void save({kind:"default"})} className="inline-flex items-center gap-2 text-xs font-medium"><RotateCcw size={13}/>Reset to default</button><button type="button" disabled={busy} onClick={()=>{setEditing(false);setDraft(null);}} className="text-xs text-muted-foreground underline">Skip for now</button>{busy&&<span role="status" className="inline-flex items-center gap-2 text-xs"><Loader2 size={14} className="animate-spin"/>Preparing or saving cover…</span>}</div>
    </div>}
  </section>;
}
