import { useEffect, useState } from "react";
import { loadHomeServices } from "./homeServicesApi";
import { defaultServiceOfferings, type ServiceOffering } from "./serviceOfferings";
import type { PricingRules } from "./AdminPricingPanel";

function MoneyInput({ cents, onChange, allowBlank=false, ...props }: { cents:number|undefined; onChange:(value:number|undefined)=>void; allowBlank?:boolean; "aria-label":string; placeholder?:string; className?:string }) {
  const [text, setText] = useState(cents == null ? "" : (cents/100).toFixed(2));
  const [focused, setFocused] = useState(false);
  useEffect(()=>{if(!focused)setText(cents == null ? "" : (cents/100).toFixed(2));},[cents,focused]);
  const valid = (allowBlank && text === "") || /^\d+(?:\.\d{0,2})?$/.test(text);
  return <span><input {...props} inputMode="decimal" value={text} aria-invalid={!valid} onFocus={()=>setFocused(true)} onBlur={()=>setFocused(false)} onChange={event=>{const value=event.target.value;setText(value);onChange(allowBlank && value === "" ? undefined : /^\d+(?:\.\d{0,2})?$/.test(value) ? Math.round(Number(value)*100) : Number.NaN);}} />{!valid ? <span role="alert" className="mt-1 block text-xs text-destructive">Enter a USD amount with up to two decimal places.</span> : null}</span>;
}
type Extra = { key:string; label:string; amount_cents:number; enabled:boolean; basis:"flat"; applies_when:string; service_ids:string[] };
type Config = { by_service?:Record<string,number>; additional_charges?:Extra[]; [key:string]:unknown };
export default function ServiceBookingFeesEditor({ rules, onChange, disabled=false }: { rules:PricingRules; onChange:(rules:PricingRules)=>void; disabled?:boolean }) {
  const [services, setServices] = useState<ServiceOffering[]>(defaultServiceOfferings());
  useEffect(() => { let cancelled=false; void loadHomeServices().then(data => { if (!cancelled && data.ok && data.offerings?.length) setServices(data.offerings); }).catch(()=>{}); return ()=>{cancelled=true;}; },[]);
  const config = (rules.professional_dispatch_pricing || {}) as Config;
  const update = (patch:Partial<Config>) => onChange({ ...rules, professional_dispatch_pricing:{ ...config,...patch } });
  const extras = config.additional_charges || [];
  const editExtra = (index:number, patch:Partial<Extra>) => update({ additional_charges:extras.map((line,i)=>i===index?{...line,...patch}:line) });
  return <fieldset disabled={disabled} className="space-y-6 rounded-2xl border border-border bg-card p-5">
    <div><h2 className="text-lg font-semibold">Booking fees by service</h2><p className="mt-2 text-sm text-muted-foreground">Blank service fees use the fallback. New authorizations show all applicable charges before consent. Existing accepted amounts stay unchanged.</p></div>
    <label className="block text-sm">Fallback booking fee (USD)<MoneyInput aria-label="Fallback booking fee" cents={Number(rules.booking_fee_cents ?? 12500)} onChange={value=>onChange({...rules,booking_fee_cents:value})} className="mt-2 min-h-11 w-full rounded-xl border border-border bg-background px-3" /></label>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{services.map(service=><label key={service.id} className="block rounded-xl border border-border p-3 text-sm"><span className="block min-h-10 font-medium">{service.name}</span><MoneyInput aria-label={`${service.name} booking fee`} allowBlank placeholder={`Fallback: $${(Number(rules.booking_fee_cents ?? 12500)/100).toFixed(2)}`} cents={config.by_service?.[service.id]} onChange={value=>{const next={...config.by_service};if(value==null)delete next[service.id];else next[service.id]=value;update({by_service:next});}} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3" /><span className="mt-2 block text-xs text-muted-foreground">Per booking · USD</span></label>)}</div>
    <div><h3 className="font-semibold">Additional charges</h3><p className="mt-1 text-sm text-muted-foreground">Flat USD amounts per booking, applied only to the selected services and timing. New rules start disabled at $0.</p></div>
    {extras.map((line,index)=><fieldset key={line.key} className="space-y-3 rounded-xl border border-border p-4"><legend className="px-2 text-sm font-semibold">Charge {index+1}</legend><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Charge name<input aria-label={`Charge ${index+1} name`} value={line.label} onChange={e=>editExtra(index,{label:e.target.value})} className="mt-1 min-h-11 w-full rounded-lg border border-border bg-background px-3" /></label><label className="text-sm">Flat amount (USD)<MoneyInput aria-label={`Charge ${index+1} amount`} cents={line.amount_cents} onChange={value=>editExtra(index,{amount_cents:value ?? Number.NaN})} className="mt-1 min-h-11 w-full rounded-lg border border-border bg-background px-3" /></label><label className="text-sm">Apply when<select aria-label={`Charge ${index+1} condition`} value={line.applies_when} onChange={e=>editExtra(index,{applies_when:e.target.value})} className="mt-1 min-h-11 w-full rounded-lg border border-border bg-background px-3"><option value="always">Every matching booking</option><option value="weekday">Scheduled weekday</option><option value="same-day">Same-day priority</option><option value="evening-weekend">Evening / weekend</option></select></label><label className="text-sm">Service scope<select aria-label={`Charge ${index+1} service scope`} value={line.service_ids[0] || ""} onChange={e=>editExtra(index,{service_ids:e.target.value?[e.target.value]:[]})} className="mt-1 min-h-11 w-full rounded-lg border border-border bg-background px-3"><option value="">All services</option>{services.map(service=><option key={service.id} value={service.id}>{service.name}</option>)}</select></label></div><div className="flex flex-wrap justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={line.enabled} onChange={e=>editExtra(index,{enabled:e.target.checked})} />Enabled</label><button type="button" onClick={()=>update({additional_charges:extras.filter((_,i)=>i!==index)})} className="min-h-11 text-sm underline">Remove charge</button></div></fieldset>)}
    <button type="button" onClick={()=>update({additional_charges:[...extras,{key:`additional_${crypto.randomUUID().replace(/-/g,"_")}`,label:"New additional charge",amount_cents:0,enabled:false,basis:"flat",applies_when:"always",service_ids:[]}]})} className="min-h-11 rounded-xl border border-border px-4 text-sm font-semibold">Add additional charge</button>
    <p className="text-xs text-muted-foreground">A $0 total requires Admin review; no payment or dispatch starts automatically.</p>
  </fieldset>;
}
