-- Local H2 smoke schema (PostgreSQL mode). Prefer Neon for full parity.
-- Applied when spring.sql.init.mode=embedded (H2 only).

CREATE TABLE IF NOT EXISTS users (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role                        VARCHAR(32)  NOT NULL,
  name                        VARCHAR(255) NOT NULL,
  email                       VARCHAR(255) NOT NULL,
  password                    VARCHAR(255) NOT NULL,
  trade                       VARCHAR(255),
  license_number              VARCHAR(255),
  license_document_name       VARCHAR(255),
  insurance_document_name     VARCHAR(255),
  id_document_name            VARCHAR(255),
  license_document_data       CLOB,
  insurance_document_data     CLOB,
  id_document_data            CLOB,
  w9_document_name            VARCHAR(255),
  w9_document_data            CLOB,
  business_registration_name  VARCHAR(255),
  business_registration_data  CLOB,
  business_license_name       VARCHAR(255),
  business_license_data       CLOB,
  diversity_document_name     VARCHAR(255),
  diversity_document_data     CLOB,
  contractor_application      CLOB,
  is_admin                    BOOLEAN NOT NULL DEFAULT FALSE,
  is_blocked                  BOOLEAN NOT NULL DEFAULT FALSE,
  compliance_status           VARCHAR(64),
  photo_data_url              CLOB,
  phone                       VARCHAR(64),
  address                     VARCHAR(512),
  address_verified            BOOLEAN DEFAULT FALSE,
  address_verified_at         TIMESTAMP WITH TIME ZONE,
  address_verification_provider VARCHAR(64),
  postal_code_plus4           VARCHAR(16),
  contact_email               VARCHAR(255),
  company_name                VARCHAR(255),
  company_details             CLOB,
  insurance_details           CLOB,
  stripe_account_id           VARCHAR(255),
  stripe_onboarding_status    VARCHAR(64),
  stripe_payouts_enabled      BOOLEAN DEFAULT FALSE,
  mfa_enabled                 BOOLEAN DEFAULT FALSE,
  plan_code                   VARCHAR(64),
  oauth_google_sub            VARCHAR(255),
  oauth_apple_sub             VARCHAR(255),
  oauth_auth0_sub             VARCHAR(255),
  google_avatar_url           VARCHAR(1024),
  signup_method               VARCHAR(32) DEFAULT 'email',
  referral_code               VARCHAR(64),
  referred_by_code            VARCHAR(64),
  admin_access_level          VARCHAR(64) DEFAULT 'read-write',
  admin_role_preset           VARCHAR(64),
  dispatch_eligible           BOOLEAN DEFAULT FALSE,
  level1_eligible             BOOLEAN DEFAULT FALSE,
  level2_eligible             BOOLEAN DEFAULT FALSE,
  overall_compliance_status   VARCHAR(32),
  license_expires_at          DATE,
  insurance_expires_at        DATE,
  service_zips                CLOB,
  travel_radius_miles         INT,
  visit_fee                   DECIMAL(12,2),
  emergency_visit_fee         DECIMAL(12,2),
  after_hours_fee             DECIMAL(12,2),
  weekend_fee                 DECIMAL(12,2),
  cancellation_fee            DECIMAL(12,2),
  minimum_labor_fee           DECIMAL(12,2),
  free_estimate               BOOLEAN DEFAULT FALSE,
  visit_applies_to_repair     BOOLEAN DEFAULT FALSE,
  gender                      VARCHAR(64),
  dob                         VARCHAR(32),
  created_at                  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at                  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (role, email)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       VARCHAR(255) NOT NULL,
  role        VARCHAR(32)  NOT NULL,
  token       VARCHAR(128) NOT NULL,
  expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  used        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_lookup
  ON password_reset_tokens (role, token, used);

CREATE TABLE IF NOT EXISTS mfa_challenges (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL,
  code_hash   VARCHAR(255) NOT NULL,
  expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
  consumed    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mfa_challenges_user
  ON mfa_challenges (user_id, consumed, expires_at);

CREATE TABLE IF NOT EXISTS conversations (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type                 VARCHAR(64),
  job_id               BIGINT,
  homeowner_user_id    BIGINT,
  contractor_user_id   BIGINT,
  subject              VARCHAR(512),
  status               VARCHAR(32) NOT NULL DEFAULT 'open',
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_conversations_homeowner
  ON conversations (homeowner_user_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_conversations_contractor
  ON conversations (contractor_user_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_conversations_type
  ON conversations (type);

CREATE TABLE IF NOT EXISTS messages (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id         BIGINT NOT NULL,
  sender_user_id          BIGINT NOT NULL,
  sender_role             VARCHAR(32),
  sender_display_name     VARCHAR(255),
  sent_by_admin_user_id   BIGINT,
  body                    CLOB NOT NULL,
  created_at              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation
  ON messages (conversation_id, created_at);

CREATE TABLE IF NOT EXISTS conversation_read_cursors (
  conversation_id  BIGINT NOT NULL,
  user_id          BIGINT NOT NULL,
  last_read_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS message_attachments (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id        BIGINT NOT NULL,
  conversation_id   BIGINT NOT NULL,
  uploader_user_id  BIGINT NOT NULL,
  file_name         VARCHAR(255) NOT NULL,
  mime_type         VARCHAR(128) NOT NULL,
  byte_size         INT NOT NULL,
  storage_data      CLOB NOT NULL,
  storage_provider  VARCHAR(64) DEFAULT 'database',
  storage_key       VARCHAR(512),
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_message_attachments_message
  ON message_attachments (message_id);

CREATE TABLE IF NOT EXISTS properties (
  id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id                   BIGINT NOT NULL,
  label                           VARCHAR(255),
  address_line1                   VARCHAR(512) NOT NULL,
  address_line2                   VARCHAR(512),
  city                            VARCHAR(128),
  state                           VARCHAR(64),
  zip                             VARCHAR(32),
  property_type                   VARCHAR(64),
  access_notes                    VARCHAR(1024),
  property_purpose                VARCHAR(128),
  transaction_stage               VARCHAR(128),
  country                         VARCHAR(64) DEFAULT 'US',
  street_address                  VARCHAR(512),
  health_profile                  CLOB,
  year_built                      INT,
  beds                            DECIMAL(8,2),
  baths                           DECIMAL(8,2),
  sqft                            INT,
  home_systems                    CLOB,
  postal_code_plus4               VARCHAR(16),
  address_verified                BOOLEAN DEFAULT FALSE,
  address_verified_at             TIMESTAMP WITH TIME ZONE,
  address_verification_provider   VARCHAR(64),
  timezone                        VARCHAR(64),
  latitude                        DOUBLE PRECISION,
  longitude                       DOUBLE PRECISION,
  created_at                      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_properties_owner
  ON properties (owner_user_id, created_at);

CREATE TABLE IF NOT EXISTS managed_jobs (
  id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id                      VARCHAR(64),
  homeowner_user_id               BIGINT NOT NULL,
  property_id                     BIGINT,
  job_mode                        VARCHAR(32) DEFAULT 'managed',
  status                          VARCHAR(64) NOT NULL DEFAULT 'draft',
  category                        VARCHAR(128),
  service_subcategory             VARCHAR(128),
  title                           VARCHAR(512),
  description                     CLOB,
  media_data_url                  CLOB,
  media_type                      VARCHAR(64),
  preferred_date                  VARCHAR(64),
  preferred_time_slot             VARCHAR(64),
  service_timing                  VARCHAR(64),
  city_state_zip                  VARCHAR(255),
  full_address                    VARCHAR(1024),
  street_address                  VARCHAR(512),
  city                            VARCHAR(128),
  state                           VARCHAR(64),
  zip                             VARCHAR(32),
  country                         VARCHAR(64) DEFAULT 'US',
  contact_name                    VARCHAR(255),
  contact_phone                   VARCHAR(64),
  ai_assessment                   CLOB,
  pricing                         CLOB,
  show_retail_price               BOOLEAN DEFAULT TRUE,
  customer_retail_estimate_low    DECIMAL(12,2),
  customer_retail_estimate_high   DECIMAL(12,2),
  estimated_contractor_net_low    DECIMAL(12,2),
  estimated_contractor_net_high   DECIMAL(12,2),
  assigned_contractor_user_id     BIGINT,
  preferred_contractor_user_id    BIGINT,
  active_proposal_id              BIGINT,
  partner_code                    VARCHAR(64),
  partner_id                      BIGINT,
  referral_source                 VARCHAR(128),
  referral_status                 VARCHAR(64),
  referring_name                  VARCHAR(255),
  referring_company               VARCHAR(255),
  referring_email                 VARCHAR(255),
  referring_phone                 VARCHAR(64),
  customer_partner_status_consent BOOLEAN DEFAULT FALSE,
  consent_timestamp               TIMESTAMP WITH TIME ZONE,
  consent_version                 VARCHAR(32),
  property_purpose                VARCHAR(128),
  transaction_stage               VARCHAR(128),
  listing_deadline                VARCHAR(64),
  closing_deadline                VARCHAR(64),
  inspection_report_url           VARCHAR(1024),
  listing_reference_url           VARCHAR(1024),
  property_opportunity_notes      CLOB,
  completion_report               CLOB,
  customer_confirmed_at           TIMESTAMP WITH TIME ZONE,
  admin_notes                     CLOB,
  discount_code                   VARCHAR(64),
  discount_type                   VARCHAR(32),
  discount_value                  DECIMAL(12,2),
  discount_label                  VARCHAR(255),
  discount_amount_low             DECIMAL(12,2),
  discount_amount_high            DECIMAL(12,2),
  assessment_status               VARCHAR(32),
  assessment_error_code           VARCHAR(64),
  assessment_attempts             INT DEFAULT 0,
  assessment_started_at           TIMESTAMP WITH TIME ZONE,
  assessment_completed_at         TIMESTAMP WITH TIME ZONE,
  diy_risk_level                  VARCHAR(32) DEFAULT 'green',
  visit_fee_authorized            BOOLEAN DEFAULT FALSE,
  visit_fee_captured              BOOLEAN DEFAULT FALSE,
  visit_fee_amount                DECIMAL(12,2),
  stripe_payment_intent_id        VARCHAR(255),
  cancellation_reason             VARCHAR(1024),
  cancellation_reason_code        VARCHAR(64),
  cancellation_details            CLOB,
  cancelled_at                    TIMESTAMP WITH TIME ZONE,
  cancelled_by                    VARCHAR(64),
  checkout_snapshot               CLOB,
  coupon_redeemed_at              TIMESTAMP WITH TIME ZONE,
  service_fee_amount              DECIMAL(12,2),
  service_amount                  DECIMAL(12,2),
  coupon_discount_amount          DECIMAL(12,2),
  final_customer_amount           DECIMAL(12,2),
  authorized_amount_cents         INT,
  payment_completed_at            TIMESTAMP WITH TIME ZONE,
  work_queue_status               VARCHAR(64),
  priority_tier                   VARCHAR(64) DEFAULT 'standard',
  estimate_confidence             VARCHAR(64),
  access_instructions             CLOB,
  assigned_employee_id            BIGINT,
  invite_deadline_at              TIMESTAMP WITH TIME ZONE,
  quote_request_mode              VARCHAR(64),
  created_at                      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at                      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_managed_jobs_booking_id
  ON managed_jobs (booking_id);
CREATE INDEX IF NOT EXISTS idx_managed_jobs_homeowner
  ON managed_jobs (homeowner_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_managed_jobs_contractor
  ON managed_jobs (assigned_contractor_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_managed_jobs_status
  ON managed_jobs (status, created_at);

CREATE TABLE IF NOT EXISTS job_invitations (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id               BIGINT NOT NULL,
  contractor_user_id   BIGINT NOT NULL,
  status               VARCHAR(64) NOT NULL DEFAULT 'invited',
  expected_net_low     DECIMAL(12,2),
  expected_net_high    DECIMAL(12,2),
  message              CLOB,
  invited_by           BIGINT,
  request_type         VARCHAR(64) DEFAULT 'remote_quote',
  site_visit_window    VARCHAR(255),
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  responded_at         TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uq_job_invitations_job_contractor UNIQUE (job_id, contractor_user_id)
);

CREATE INDEX IF NOT EXISTS idx_job_invitations_contractor
  ON job_invitations (contractor_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_job_invitations_job
  ON job_invitations (job_id);

CREATE TABLE IF NOT EXISTS notifications (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL,
  user_role    VARCHAR(32),
  job_id       BIGINT,
  type         VARCHAR(80) NOT NULL,
  title        VARCHAR(255) NOT NULL,
  message      CLOB NOT NULL,
  entity_type  VARCHAR(64),
  entity_id    BIGINT,
  action_url   VARCHAR(512),
  metadata     CLOB,
  "read"       BOOLEAN DEFAULT FALSE,
  read_at      TIMESTAMP WITH TIME ZONE,
  archived_at  TIMESTAMP WITH TIME ZONE,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
  ON notifications (user_id, "read", archived_at, created_at);

CREATE TABLE IF NOT EXISTS proposals (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id                    BIGINT NOT NULL,
  bid_id                    BIGINT,
  scope_summary             CLOB,
  retail_amount             DECIMAL(12,2) NOT NULL,
  deposit_amount            DECIMAL(12,2),
  timeline                  CLOB,
  warranty                  CLOB,
  exclusions                CLOB,
  contractor_net            DECIMAL(12,2),
  platform_gross            DECIMAL(12,2),
  processing_cost           DECIMAL(12,2),
  status                    VARCHAR(64) NOT NULL DEFAULT 'draft',
  created_by                BIGINT,
  published_at              TIMESTAMP WITH TIME ZONE,
  approved_at               TIMESTAMP WITH TIME ZONE,
  line_items                CLOB,
  customer_line_items       CLOB,
  pricing_adjustments       CLOB,
  admin_discount            DECIMAL(12,2),
  admin_discount_reason     VARCHAR(512),
  coupon_code               VARCHAR(64),
  quote_valid_until         TIMESTAMP WITH TIME ZONE,
  service_charge            DECIMAL(12,2),
  quote_number              VARCHAR(64),
  shipping_amount           DECIMAL(12,2),
  quote_option_label        VARCHAR(32),
  quote_option_title        VARCHAR(255),
  option_group              VARCHAR(64),
  option_selection_status   VARCHAR(64) DEFAULT 'pending',
  version_number            INT DEFAULT 1,
  contractor_quote_amount   DECIMAL(12,2),
  converted_invoice_id      BIGINT,
  locked_at                 TIMESTAMP WITH TIME ZONE,
  accepted_snapshot_id      BIGINT,
  document_totals           CLOB,
  created_at                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_proposals_job
  ON proposals (job_id, created_at);

CREATE TABLE IF NOT EXISTS change_orders (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id               BIGINT NOT NULL,
  contractor_user_id   BIGINT,
  description          CLOB NOT NULL,
  media_data_url       CLOB,
  contractor_net       DECIMAL(12,2) NOT NULL,
  retail_amount        DECIMAL(12,2),
  status               VARCHAR(64) NOT NULL DEFAULT 'submitted',
  reason               CLOB,
  line_items           CLOB,
  approved_snapshot    CLOB,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  approved_at          TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_change_orders_job
  ON change_orders (job_id, created_at);

CREATE TABLE IF NOT EXISTS diy_projects (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id           BIGINT NOT NULL,
  job_id            BIGINT,
  title             VARCHAR(255) NOT NULL,
  plan              CLOB NOT NULL,
  steps_completed   CLOB,
  status            VARCHAR(64) NOT NULL DEFAULT 'active',
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_diy_projects_user
  ON diy_projects (user_id, updated_at);

CREATE TABLE IF NOT EXISTS diy_safety_events (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               BIGINT NOT NULL,
  job_id                BIGINT,
  event_type            VARCHAR(80) NOT NULL,
  risk_level            VARCHAR(32),
  previous_risk_level   VARCHAR(32),
  risk_reason_codes     CLOB,
  feedback_rating       VARCHAR(40),
  incident_type         VARCHAR(64),
  description           CLOB,
  metadata              CLOB,
  ip_address            VARCHAR(128),
  user_agent            VARCHAR(512),
  source_route          VARCHAR(512),
  created_at            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_diy_safety_events_user
  ON diy_safety_events (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_diy_safety_events_job
  ON diy_safety_events (job_id, created_at);

CREATE TABLE IF NOT EXISTS payments (
  id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id                          BIGINT,
  user_id                         BIGINT,
  payment_type                    VARCHAR(64) NOT NULL,
  amount                          DECIMAL(12,2) NOT NULL,
  currency                        VARCHAR(16) DEFAULT 'usd',
  status                          VARCHAR(64) NOT NULL DEFAULT 'pending',
  stripe_session_id               VARCHAR(255),
  stripe_payment_intent           VARCHAR(255),
  stripe_subscription_id          VARCHAR(255),
  stripe_charge_id                VARCHAR(255),
  stripe_balance_transaction_id   VARCHAR(255),
  stripe_processing_fee_cents     INT,
  stripe_net_received_cents       INT,
  simulated                       BOOLEAN DEFAULT FALSE,
  meta                            CLOB,
  public_id                       VARCHAR(64),
  provider                        VARCHAR(32) DEFAULT 'stripe',
  created_at                      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_public_id
  ON payments (public_id);
CREATE INDEX IF NOT EXISTS idx_payments_job
  ON payments (job_id, created_at);
CREATE INDEX IF NOT EXISTS idx_payments_user
  ON payments (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_payments_stripe_session
  ON payments (stripe_session_id);

CREATE TABLE IF NOT EXISTS webhook_events (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider             VARCHAR(64) NOT NULL,
  event_id             VARCHAR(255) NOT NULL,
  type                 VARCHAR(128),
  processed            BOOLEAN DEFAULT FALSE,
  payload              CLOB,
  processing_status    VARCHAR(32) DEFAULT 'received',
  attempt_count        INT DEFAULT 0,
  last_error           CLOB,
  processed_at         TIMESTAMP WITH TIME ZONE,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_webhook_provider_event UNIQUE (provider, event_id)
);

CREATE TABLE IF NOT EXISTS pricing_rules (
  id          VARCHAR(64) PRIMARY KEY,
  rules       CLOB NOT NULL,
  updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscription_plans (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          VARCHAR(64) UNIQUE NOT NULL,
  name          VARCHAR(120) NOT NULL,
  amount        DECIMAL(10,2) NOT NULL DEFAULT 0,
  interval      VARCHAR(16) NOT NULL DEFAULT 'month',
  theme         VARCHAR(32) NOT NULL DEFAULT 'light',
  sort_order    INT NOT NULL DEFAULT 0,
  features      CLOB NOT NULL,
  highlight     BOOLEAN NOT NULL DEFAULT FALSE,
  unlocks_diy   BOOLEAN NOT NULL DEFAULT FALSE,
  trial_days    INT NOT NULL DEFAULT 0,
  active        BOOLEAN NOT NULL DEFAULT TRUE,
  cta_label     VARCHAR(64) NOT NULL DEFAULT 'Select',
  description   CLOB,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                  BIGINT NOT NULL,
  plan_code                VARCHAR(64) NOT NULL,
  plan_family              VARCHAR(64) NOT NULL,
  status                   VARCHAR(64) DEFAULT 'active',
  stripe_subscription_id   VARCHAR(255),
  current_period_end       TIMESTAMP WITH TIME ZONE,
  simulated                BOOLEAN DEFAULT FALSE,
  meta                     CLOB,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_user
  ON subscriptions (user_id, created_at);

CREATE TABLE IF NOT EXISTS homecare_settings (
  id              VARCHAR(64) PRIMARY KEY,
  config          CLOB NOT NULL,
  config_version  INT NOT NULL DEFAULT 1,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_by      BIGINT
);

CREATE TABLE IF NOT EXISTS recurring_services (
  id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id                BIGINT NOT NULL,
  property_id                  BIGINT NOT NULL,
  service_type                 VARCHAR(64) NOT NULL,
  recurrence                   VARCHAR(64) NOT NULL,
  preferred_day                VARCHAR(64),
  preferred_time_window        VARCHAR(64),
  start_date                   DATE,
  status                       VARCHAR(32) NOT NULL DEFAULT 'active',
  next_service_date            DATE,
  assigned_contractor_user_id  BIGINT,
  notes                        CLOB,
  metadata                     CLOB,
  created_at                   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at                   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_recurring_services_owner
  ON recurring_services (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_recurring_services_property
  ON recurring_services (property_id);

CREATE TABLE IF NOT EXISTS support_tickets (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_number         VARCHAR(64) UNIQUE NOT NULL,
  user_id               BIGINT NOT NULL,
  user_role             VARCHAR(32),
  user_name             VARCHAR(255),
  user_email            VARCHAR(255) NOT NULL,
  user_phone            VARCHAR(64),
  channel               VARCHAR(32) NOT NULL,
  subject               VARCHAR(255) NOT NULL,
  message               CLOB NOT NULL,
  category              VARCHAR(80),
  priority              VARCHAR(32) NOT NULL DEFAULT 'normal',
  assigned_to           VARCHAR(128),
  related_property_id   BIGINT,
  related_job_id        BIGINT,
  related_quote_id      BIGINT,
  related_invoice_id    BIGINT,
  related_payment_id    BIGINT,
  context               CLOB,
  status                VARCHAR(64) NOT NULL DEFAULT 'open',
  created_at            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  resolved_at           TIMESTAMP WITH TIME ZONE,
  closed_at             TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_support_tickets_user
  ON support_tickets (user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status
  ON support_tickets (status, updated_at);

CREATE TABLE IF NOT EXISTS support_ticket_messages (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id       BIGINT NOT NULL,
  sender_user_id  BIGINT,
  sender_role     VARCHAR(32) NOT NULL,
  sender_name     VARCHAR(255),
  message         CLOB NOT NULL,
  is_internal     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_support_ticket_messages_ticket
  ON support_ticket_messages (ticket_id, created_at);

CREATE TABLE IF NOT EXISTS legal_document_versions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_key     VARCHAR(128) NOT NULL,
  title            VARCHAR(255) NOT NULL,
  version          VARCHAR(64) NOT NULL,
  effective_date   DATE NOT NULL,
  status           VARCHAR(32) NOT NULL DEFAULT 'current',
  route            VARCHAR(255),
  audience         VARCHAR(64) DEFAULT 'public',
  content          CLOB NOT NULL,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_by       BIGINT,
  CONSTRAINT uq_legal_doc_key_version UNIQUE (document_key, version)
);

CREATE INDEX IF NOT EXISTS idx_legal_doc_versions_key_status
  ON legal_document_versions (document_key, status, effective_date);

CREATE TABLE IF NOT EXISTS homeowner_acceptances (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              BIGINT NOT NULL,
  guest_session_id     VARCHAR(128),
  job_id               BIGINT,
  quote_id             BIGINT,
  change_order_id      BIGINT,
  payment_id           BIGINT,
  acceptance_type      VARCHAR(128) NOT NULL,
  document_key         VARCHAR(128),
  document_version     VARCHAR(64) NOT NULL,
  document_title       VARCHAR(255),
  accepted             BOOLEAN NOT NULL DEFAULT TRUE,
  accepted_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata             CLOB,
  snapshot_id          BIGINT,
  snapshot_data        CLOB,
  action_completed     BOOLEAN NOT NULL DEFAULT TRUE,
  idempotency_key      VARCHAR(255) UNIQUE,
  ip_address           VARCHAR(128),
  user_agent           VARCHAR(512),
  source_route         VARCHAR(512),
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_homeowner_acceptances_user_type
  ON homeowner_acceptances (user_id, acceptance_type, document_version, accepted_at);

CREATE TABLE IF NOT EXISTS service_offerings (
  id                       VARCHAR(64) PRIMARY KEY,
  slug                     VARCHAR(64) NOT NULL UNIQUE,
  name                     VARCHAR(120) NOT NULL,
  description              VARCHAR(512) NOT NULL,
  icon_key                 VARCHAR(64),
  one_time_professional    BOOLEAN NOT NULL DEFAULT TRUE,
  diy_eligible             BOOLEAN NOT NULL DEFAULT TRUE,
  ai_assessment_eligible   BOOLEAN NOT NULL DEFAULT TRUE,
  subscription_eligible    BOOLEAN NOT NULL DEFAULT FALSE,
  emergency_eligible       BOOLEAN NOT NULL DEFAULT FALSE,
  active                   BOOLEAN NOT NULL DEFAULT TRUE,
  homeowner_visible        BOOLEAN NOT NULL DEFAULT TRUE,
  pricing_metadata         CLOB,
  sort_order               INT NOT NULL DEFAULT 0,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_service_offerings_visible
  ON service_offerings (active, homeowner_visible, sort_order);

CREATE INDEX IF NOT EXISTS idx_service_offerings_sort
  ON service_offerings (sort_order, name);

CREATE TABLE IF NOT EXISTS bids (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id               BIGINT NOT NULL,
  contractor_user_id   BIGINT NOT NULL,
  net_total            DECIMAL(12,2) NOT NULL,
  labor_amount         DECIMAL(12,2),
  materials_amount     DECIMAL(12,2),
  timeline             CLOB,
  warranty             CLOB,
  exclusions           CLOB,
  notes                CLOB,
  status               VARCHAR(64) DEFAULT 'submitted',
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_bids_job ON bids (job_id, created_at);

CREATE TABLE IF NOT EXISTS quote_revision_snapshots (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proposal_id          BIGINT NOT NULL,
  version_number       INT NOT NULL,
  change_reason        VARCHAR(1024),
  document_snapshot    CLOB NOT NULL,
  customer_total       DECIMAL(12,2),
  contractor_amount    DECIMAL(12,2),
  created_by           BIGINT,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_quote_revision_proposal_version UNIQUE (proposal_id, version_number)
);
CREATE INDEX IF NOT EXISTS idx_quote_revision_snapshots_proposal
  ON quote_revision_snapshots (proposal_id, version_number);

CREATE TABLE IF NOT EXISTS contractor_payouts (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contractor_id            BIGINT NOT NULL,
  job_id                   BIGINT NOT NULL,
  job_ref                  VARCHAR(64),
  customer_label           VARCHAR(512),
  completion_date          TIMESTAMP WITH TIME ZONE,
  gross_amount_cents       INT NOT NULL DEFAULT 0,
  platform_fee_cents       INT NOT NULL DEFAULT 0,
  instant_payout_fee_cents INT NOT NULL DEFAULT 0,
  adjustments_cents        INT NOT NULL DEFAULT 0,
  net_amount_cents         INT NOT NULL DEFAULT 0,
  reserve_amount_cents     INT NOT NULL DEFAULT 0,
  service_amount_cents     INT NOT NULL DEFAULT 0,
  tip_amount_cents         INT NOT NULL DEFAULT 0,
  payout_method            VARCHAR(32) DEFAULT 'standard',
  stripe_transfer_id       VARCHAR(255),
  stripe_payout_id         VARCHAR(255),
  status                   VARCHAR(64) NOT NULL DEFAULT 'pending_approval',
  hold_reason              VARCHAR(1024),
  held_at                  TIMESTAMP WITH TIME ZONE,
  approved_by              BIGINT,
  approved_at              TIMESTAMP WITH TIME ZONE,
  paid_at                  TIMESTAMP WITH TIME ZONE,
  estimated_payout_at      TIMESTAMP WITH TIME ZONE,
  failure_reason           CLOB,
  created_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at               TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_contractor_payouts_job UNIQUE (job_id)
);
CREATE INDEX IF NOT EXISTS idx_contractor_payouts_contractor
  ON contractor_payouts (contractor_id, created_at);
CREATE INDEX IF NOT EXISTS idx_contractor_payouts_status
  ON contractor_payouts (status, created_at);

CREATE TABLE IF NOT EXISTS payout_settings (
  id                           VARCHAR(32) PRIMARY KEY,
  instant_payout_enabled       BOOLEAN DEFAULT TRUE,
  instant_fee_type             VARCHAR(64) DEFAULT 'percentage_plus_fixed',
  instant_fee_percentage_bps   INT DEFAULT 200,
  instant_fee_fixed_cents      INT DEFAULT 150,
  minimum_instant_fee_cents    INT DEFAULT 50,
  maximum_instant_fee_cents    INT DEFAULT 2500,
  minimum_instant_payout_cents INT DEFAULT 1000,
  maximum_instant_payout_cents INT DEFAULT 1000000,
  contractor_absorbs_fee       BOOLEAN DEFAULT TRUE,
  fixbridge_absorbs_fee        BOOLEAN DEFAULT FALSE,
  updated_by                   BIGINT,
  updated_at                   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO payout_settings (id) SELECT 'default'
  WHERE NOT EXISTS (SELECT 1 FROM payout_settings WHERE id = 'default');

CREATE TABLE IF NOT EXISTS payout_audit_logs (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payout_id        BIGINT NOT NULL,
  action           VARCHAR(64) NOT NULL,
  previous_status  VARCHAR(64),
  new_status       VARCHAR(64),
  performed_by     BIGINT,
  metadata         CLOB,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payout_audit_logs_payout
  ON payout_audit_logs (payout_id, created_at);

CREATE TABLE IF NOT EXISTS disputes (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id            BIGINT,
  job_id                BIGINT,
  stripe_dispute_id     VARCHAR(255),
  amount                DECIMAL(12,2),
  reason                VARCHAR(1024),
  category              VARCHAR(64),
  description           CLOB,
  preferred_resolution  VARCHAR(512),
  status                VARCHAR(64) DEFAULT 'open',
  meta                  CLOB,
  opened_by_user_id     BIGINT,
  opened_by_role        VARCHAR(32),
  homeowner_user_id     BIGINT,
  contractor_user_id    BIGINT,
  assigned_employee_id  BIGINT,
  created_at            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_disputes_job ON disputes (job_id, created_at);
CREATE INDEX IF NOT EXISTS idx_disputes_status ON disputes (status, created_at);

CREATE TABLE IF NOT EXISTS dispute_events (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dispute_id      BIGINT NOT NULL,
  actor_user_id   BIGINT,
  actor_role      VARCHAR(32),
  action          VARCHAR(64) NOT NULL,
  reason          CLOB,
  before_state    CLOB,
  after_state     CLOB,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dispute_events_dispute
  ON dispute_events (dispute_id, created_at);

CREATE TABLE IF NOT EXISTS refunds (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id        BIGINT,
  job_id            BIGINT,
  amount            DECIMAL(12,2) NOT NULL,
  reason            CLOB,
  status            VARCHAR(64) DEFAULT 'pending',
  stripe_refund_id  VARCHAR(255),
  simulated         BOOLEAN DEFAULT FALSE,
  created_by        BIGINT,
  idempotency_key   VARCHAR(255),
  ledger_note       CLOB,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_refunds_idempotency ON refunds (idempotency_key);
CREATE INDEX IF NOT EXISTS idx_refunds_payment ON refunds (payment_id);
CREATE INDEX IF NOT EXISTS idx_refunds_job ON refunds (job_id);

CREATE TABLE IF NOT EXISTS payment_authorization_snapshots (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id                 BIGINT NOT NULL,
  job_id                  BIGINT,
  payment_id              BIGINT,
  authorized_amount_cents INT NOT NULL,
  currency                VARCHAR(16) DEFAULT 'usd',
  policy_document_version VARCHAR(64),
  acceptance_id           BIGINT,
  created_at              TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payment_auth_snapshots_job
  ON payment_authorization_snapshots (job_id, created_at);

CREATE TABLE IF NOT EXISTS job_tips (
  id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id                    BIGINT NOT NULL,
  homeowner_user_id         BIGINT,
  contractor_user_id        BIGINT,
  amount                    DECIMAL(12,2) NOT NULL,
  percent_of_service        DECIMAL(8,4),
  status                    VARCHAR(32) NOT NULL DEFAULT 'pending',
  stripe_payment_intent_id  VARCHAR(255),
  paid_at                   TIMESTAMP WITH TIME ZONE,
  created_at                TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_job_tips_job ON job_tips (job_id, created_at);

CREATE TABLE IF NOT EXISTS financial_ledger_events (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type       VARCHAR(80) NOT NULL,
  job_id           BIGINT,
  payment_id       BIGINT,
  payout_id        BIGINT,
  contractor_id    BIGINT,
  amount_cents     INT,
  stripe_object_id VARCHAR(255),
  created_by       BIGINT,
  metadata         CLOB,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_financial_ledger_job
  ON financial_ledger_events (job_id, created_at);


-- Contractor compliance
CREATE TABLE IF NOT EXISTS contractor_compliance_documents (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contractor_user_id   BIGINT NOT NULL,
  document_type        VARCHAR(64) NOT NULL,
  applicability        VARCHAR(32) NOT NULL DEFAULT 'REQUIRED',
  status               VARCHAR(32) NOT NULL DEFAULT 'MISSING',
  file_name            VARCHAR(255),
  file_data            CLOB,
  issue_date           DATE,
  expiration_date      DATE,
  upload_later         BOOLEAN DEFAULT FALSE,
  uploaded_at          TIMESTAMP WITH TIME ZONE,
  verified_at          TIMESTAMP WITH TIME ZONE,
  verified_by          BIGINT,
  rejected_at          TIMESTAMP WITH TIME ZONE,
  rejected_by          BIGINT,
  rejection_reason     CLOB,
  notes                CLOB,
  policy_carrier       VARCHAR(255),
  policy_number        VARCHAR(255),
  version              INT NOT NULL DEFAULT 1,
  is_current           BOOLEAN NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_contractor_compliance_current
  ON contractor_compliance_documents (contractor_user_id, document_type, is_current);

CREATE TABLE IF NOT EXISTS contractor_compliance_events (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contractor_user_id   BIGINT NOT NULL,
  document_type        VARCHAR(64),
  action               VARCHAR(128) NOT NULL,
  actor_user_id        BIGINT,
  metadata             CLOB,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_contractor_compliance_events_user
  ON contractor_compliance_events (contractor_user_id, created_at);

CREATE TABLE IF NOT EXISTS contractor_compliance_alerts (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contractor_user_id   BIGINT NOT NULL,
  document_type        VARCHAR(64) NOT NULL,
  alert_type           VARCHAR(64) NOT NULL,
  expiration_date      DATE,
  sent_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  recipient_role       VARCHAR(32) NOT NULL DEFAULT 'contractor',
  recipient_email      VARCHAR(255)
);
CREATE INDEX IF NOT EXISTS idx_contractor_compliance_alerts_user
  ON contractor_compliance_alerts (contractor_user_id, document_type);

-- Contractor employees / field team
CREATE TABLE IF NOT EXISTS contractor_employees (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contractor_user_id   BIGINT NOT NULL,
  full_name            VARCHAR(255) NOT NULL,
  job_title            VARCHAR(255),
  bio                  CLOB,
  trade                VARCHAR(128),
  years_experience     INT,
  employee_ref         VARCHAR(128),
  photo_data           CLOB,
  photo_mime           VARCHAR(64),
  customer_description CLOB,
  internal_notes       CLOB,
  phones               CLOB NOT NULL DEFAULT '[]',
  emails               CLOB NOT NULL DEFAULT '[]',
  active               BOOLEAN NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_contractor_employees_company
  ON contractor_employees (contractor_user_id, active);

-- Availability
CREATE TABLE IF NOT EXISTS contractor_availability (
  contractor_user_id     BIGINT PRIMARY KEY,
  timezone               VARCHAR(64) DEFAULT 'America/New_York',
  working_days           CLOB,
  same_day_available     BOOLEAN DEFAULT FALSE,
  emergency_available    BOOLEAN DEFAULT FALSE,
  max_jobs_per_day       INT,
  temporary_unavailable  BOOLEAN DEFAULT FALSE,
  updated_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_availability (
  employee_id            BIGINT PRIMARY KEY,
  contractor_user_id     BIGINT NOT NULL,
  working_hours          CLOB,
  unavailable_dates      CLOB DEFAULT '[]',
  temporary_unavailable  BOOLEAN DEFAULT FALSE,
  service_areas          CLOB DEFAULT '[]',
  updated_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Partners
CREATE TABLE IF NOT EXISTS partners (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        VARCHAR(64) NOT NULL UNIQUE,
  name        VARCHAR(255) NOT NULL,
  company     VARCHAR(255),
  email       VARCHAR(255),
  phone       VARCHAR(64),
  notes       CLOB,
  active      BOOLEAN DEFAULT TRUE,
  deleted_at  TIMESTAMP WITH TIME ZONE,
  created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS partner_users (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id     BIGINT NOT NULL,
  email          VARCHAR(255) NOT NULL,
  name           VARCHAR(255),
  password_hash  VARCHAR(255),
  role           VARCHAR(32) DEFAULT 'partner',
  created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_partner_users_partner_email UNIQUE (partner_id, email)
);

CREATE TABLE IF NOT EXISTS partner_referrals (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id         BIGINT,
  partner_code       VARCHAR(64),
  job_id             BIGINT,
  homeowner_user_id  BIGINT,
  status             VARCHAR(64) DEFAULT 'referral_received',
  created_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Referrals
CREATE TABLE IF NOT EXISTS referral_settings (
  id         VARCHAR(32) PRIMARY KEY,
  config     CLOB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT
);
INSERT INTO referral_settings (id, config) SELECT 'default',
  '{"homeowner_homeowner":{"referrerRewardCents":10000,"referredRewardCents":10000,"rewardType":"credit","qualifyOn":"first_paid_service"},"contractor_customer":{"contractorRewardCents":10000,"rewardType":"payout_bonus","qualifyOn":"first_paid_service"},"contractor_contractor":{"contractorRewardCents":7500,"rewardType":"payout_bonus","qualifyOn":"approved_and_first_completed_job"},"combineWithCoupons":false,"maxCreditPerInvoiceCents":10000,"combineMultipleCredits":true}'
  WHERE NOT EXISTS (SELECT 1 FROM referral_settings WHERE id = 'default');

CREATE TABLE IF NOT EXISTS referral_relationships (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id              VARCHAR(64) UNIQUE,
  type                   VARCHAR(64) NOT NULL,
  referrer_user_id       BIGINT NOT NULL,
  referred_user_id       BIGINT,
  referral_code          VARCHAR(64) NOT NULL,
  status                 VARCHAR(64) NOT NULL DEFAULT 'signed_up',
  referrer_reward_cents  INT NOT NULL DEFAULT 0,
  referred_reward_cents  INT NOT NULL DEFAULT 0,
  reward_type            VARCHAR(32) NOT NULL DEFAULT 'credit',
  qualification_event    VARCHAR(128),
  related_job_id         BIGINT,
  qualified_at           TIMESTAMP WITH TIME ZONE,
  reward_earned_at       TIMESTAMP WITH TIME ZONE,
  reward_available_at    TIMESTAMP WITH TIME ZONE,
  reward_used_at         TIMESTAMP WITH TIME ZONE,
  invalid_reason         CLOB,
  hold_reason            CLOB,
  created_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_referral_rel_referred_unique
  ON referral_relationships (referred_user_id);
CREATE INDEX IF NOT EXISTS idx_referral_rel_referrer
  ON referral_relationships (referrer_user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_referral_rel_code
  ON referral_relationships (referral_code);

CREATE TABLE IF NOT EXISTS referral_credits (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          BIGINT NOT NULL,
  relationship_id  BIGINT,
  amount_cents     INT NOT NULL,
  kind             VARCHAR(32) NOT NULL,
  status           VARCHAR(32) NOT NULL DEFAULT 'available',
  related_job_id   BIGINT,
  note             CLOB,
  created_by       BIGINT,
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_referral_credits_user
  ON referral_credits (user_id, created_at);

CREATE TABLE IF NOT EXISTS referral_payout_bonuses (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contractor_user_id  BIGINT NOT NULL,
  relationship_id     BIGINT NOT NULL UNIQUE,
  amount_cents        INT NOT NULL,
  bonus_type          VARCHAR(64) NOT NULL,
  status              VARCHAR(32) NOT NULL DEFAULT 'available',
  note                CLOB,
  created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  paid_at             TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS referral_notes (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relationship_id   BIGINT NOT NULL,
  author_user_id    BIGINT,
  author_label      VARCHAR(128) NOT NULL DEFAULT 'System',
  body              CLOB NOT NULL,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS referral_code_meta (
  user_id         BIGINT PRIMARY KEY,
  code            VARCHAR(64) NOT NULL UNIQUE,
  disabled        BOOLEAN DEFAULT FALSE,
  regenerated_at  TIMESTAMP WITH TIME ZONE,
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Admin / commerce tables (Angular admin + homeowner)
CREATE TABLE IF NOT EXISTS discount_codes (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code            VARCHAR(64) NOT NULL,
  label           VARCHAR(255),
  discount_type   VARCHAR(32) NOT NULL DEFAULT 'percent',
  value           DECIMAL(12,2) NOT NULL,
  active          BOOLEAN DEFAULT TRUE,
  max_uses        INT,
  uses_count      INT DEFAULT 0,
  expires_at      TIMESTAMP WITH TIME ZONE,
  starts_at       TIMESTAMP WITH TIME ZONE,
  deleted_at      TIMESTAMP WITH TIME ZONE,
  notes           CLOB,
  per_user_limit  INT,
  created_by      BIGINT,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_discount_codes_code_lower
  ON discount_codes (LOWER(code));

CREATE TABLE IF NOT EXISTS audit_logs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id   BIGINT,
  action          VARCHAR(128) NOT NULL,
  entity_type     VARCHAR(64),
  entity_id       VARCHAR(64),
  detail          CLOB,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created
  ON audit_logs (created_at DESC);

CREATE TABLE IF NOT EXISTS property_documents (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id     BIGINT NOT NULL,
  owner_user_id   BIGINT NOT NULL,
  category        VARCHAR(64) NOT NULL,
  title           VARCHAR(255),
  file_name       VARCHAR(255),
  mime_type       VARCHAR(128),
  data_url        CLOB NOT NULL,
  notes           CLOB,
  system_key      VARCHAR(128),
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_property_documents_owner
  ON property_documents (property_id, owner_user_id, created_at);

CREATE TABLE IF NOT EXISTS media_objects (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id   BIGINT,
  job_id          BIGINT,
  kind            VARCHAR(64),
  storage_key     VARCHAR(512),
  content_type    VARCHAR(128),
  byte_size       INT,
  data_url        CLOB,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_media_objects_owner
  ON media_objects (owner_user_id, created_at);
